services:
  postgres:
    image: postgres:16-alpine
    container_name: harbor-postgres
    environment:
      POSTGRES_USER: harbor_admin
      POSTGRES_PASSWORD: harbor_password
      POSTGRES_DB: harbor_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../bootstrap/postgres/01-init-dbs.sql:/docker-entrypoint-initdb.d/01-init-dbs.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U harbor_admin -d harbor_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - harbor-net

volumes:
  postgres_data:

networks:
  harbor-net:
    driver: bridge
